# Project identification
sonar.organization=josesuite
sonar.projectName=jose-node
sonar.projectKey=jose-node
sonar.projectVersion=1.0

# Source configuration
sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

# Coverage configuration
sonar.typescript.lcov.reportPaths=lcov.info

# Exclude directories from analysis
sonar.exclusions=dist/**,node_modules/**
